spring:
  application:
    name: NotificationService
  data:
    mongodb:
      uri: ${DB_URI_CONNECTION:mongodb://root:root@localhost:27017/notification-service-data?authSource=admin}

server:
  port: 9003
  servlet:
    context-path: /notification

app:
  config:
    mail:
      api-key: ${BREVO_EMAIL_KEY}
      sender-email: ${BREVO_SENDER_EMAIL:todinhvan2608@gmail.com}
      sender-name: ${BREVO_SENDER_NAME:Van}