spring:
  application:
    name: IdentityService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identity_data?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9001
  servlet:
    context-path: /identity

app:
  config:
    jwt-secret: ${APP_CONFIG_JWT_SECRET}
    token-expire-time: 5 # 5 second
    refresh-token-expire-time: 240 # 240 second
  default:
    user:
      email: ${APP_DEFAULT_USER_EMAIL}
      password: ${APP_DEFAULT_USER_PASSWORD}
    cron:
      clean-blacklist-token-expired: "0 0 0 * * *"
