spring:
  application:
    name: IdentityService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_data?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 9001
  servlet:
    context-path: /identity

app:
  config:
    jwt-secret: ${APP_CONFIG_JWT_SECRET:e485b5240ec08b54456b810ec95b5c47b9baf0878bd9e5121a4d09aeba978aa9}
    token-expire-time: 60 # 60 minutes
    refresh-token-expire-time: 1440 # 1440 minutes
  default:
    user:
      email: ${APP_DEFAULT_USER_EMAIL:admin@gmail.com}
      password: ${APP_DEFAULT_USER_PASSWORD:1234}
    cron:
      clean-blacklist-token-expired: "0 0 0 * * *"
  services:
    profile: http://localhost:9002/profiles
    google-oauth2:
      token-uri: https://oauth2.googleapis.com
      profile-uri: https://www.googleapis.com
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
      grant-type: authorization_code
      redirect-uri: http://localhost:3000/authenticate
