spring:
  application:
    name: FileService
  data:
    mongodb:
      uri: ${DB_URI_CONNECTION:mongodb://root:root@localhost:27017/file-service-data?authSource=admin}

server:
  port: 9005

app:
  config:
    file:
      storage-dir: D:/upload
      download-prefix: http://localhost:9000/api/v1/file/
