spring:
  application:
    name: ProfileService
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 9002
  servlet:
    context-path: /profiles

app:
  services:
    identity: http://localhost:9001/identity
    file: http://localhost:9005/file